### ISSUE TITLE
services .zinio.com: no such host

### ISSUE THREAD

**Issue by th3bl4cksmith** [Metalnem/zinio#1]
I get this error on Windows 7:

failed to authenticate user xxx@xxxxx.com: Post https://services.zinio.com/newsstandServices/authenticateUser: dial tcp: lookup services.zinio.com: no such host

**Comment by Metalnem** [comment]
I couldn't reproduce this. Zinio servers are often unreliable -- did you try to wait and retry later?

**Comment by th3bl4cksmith** [comment]
Yes, I'm still getting the same error. Tried on Ubuntu 17.04 and I'm getting:

INFO[0000] logging in                                    user="xxx@xxxxx.com"
FATA[0060] failed to authenticate user xxx@xxxxx.com: Post https://services.zinio.com/newsstandServices/authenticateUser: dial tcp: lookup services.zinio.com on 127.0.1.1:53: read udp 127.0.0.1:39111->127.0.1.1:53: read: connection refused

**Comment by Metalnem** [comment]
Looks like some kind of DNS issue. Can you open <https://services.zinio.com/> from your browser and tell me what happens? Can you also run the command `dig services.zinio.com` in the terminal and send me the output?
