### ISSUE TITLE
New issues not being detected 

### ISSUE THREAD

**Issue by remicarreiro** [Metalnem/zinio#11]
Thank you for this awesome tool. I have issues from a couple of different magazines but the tool only seems to download all the issues of one magazine and forget about the others. Is there anything you can think of that I could change?

**Comment by Metalnem** [comment]
Do you have more than 500 magazines in your library (that's the limit in mobile Zinio apps)? Is it always the same magazines that are being ignored? Can you also give me a few examples of ignored magazines?

**Comment by remicarreiro** [comment]
Hi,

I don’t have that many. I have 24 issues from Mark Magazine which I was able to download successfully. But the couple of issues from El Croquis that I have, issues 131-132 and 134-135; I haven’t been able to download. Maybe it has something to do with them being older issues? Like many years old.

Rémi Carreiro

**Comment by Metalnem** [comment]
It actually happens with very old issues. You can try to download the Zinio iOS or Windows Store app—if the magazine is not there, then it's problem on the Zinio side. They are in the process of switching to new format for the new desktop and web apps, and the old format is not getting much love.

**Comment by remicarreiro** [comment]
Alright. I tried the iOS app and managed to download issue 131-132 of El Croquis within the app but it still isn't downloading through the tool. Guess I just won't be able to get that one; too bad really. Was really wanting those older issues as PDFs.

**Comment by Metalnem** [comment]
I forgot to ask the important question: does my tool see these magazines and fails to download them, or just completely ignores them?

**Comment by remicarreiro** [comment]
The tool ignored the El Croquis issue completely. It doesn't appear in the list at all. I just tried using the tool again now to double check but I am receiving the following error.

![capture](https://user-images.githubusercontent.com/4554673/32785947-bb44f4b0-c920-11e7-81f5-bc651a3b7498.PNG)

**Comment by Metalnem** [comment]
That happens sometimes, and the solution is to try again later. Anyway, if the tool doesn’t show the magazines, it means that the server didn’t send them, so there is not much that I can do here.
