### ISSUE TITLE
failed to save Magazine_Name.pdf: rename C:\Users\user\AppData\Local\Temp\31103143 Magazine_Name.pdf: The system cannot move the file to a different disk drive.

### ISSUE THREAD

**Issue by JRBERNSTEIN** [Metalnem/zinio#12]
I keep getting the following error:

> failed to save Magazine_Name.pdf: rename C:\Users\user\AppData\Local\Temp\31103143 Magazine_Name.pdf: The system cannot move the file to a different disk drive.

Any way to use this awesome tool on a drive other than C: on Windows? I don't have nearly enough space to save my library on C: but I have plenty of space on other drives.

Thanks!

**Comment by Metalnem** [comment]
This looks like you are not running the up-to-date version of the tool. Just download the latest version, and run it from directory where you want to save your magazines.
