### ISSUE TITLE
very often of error "failed to download page #: context deadline exceeded"

### ISSUE THREAD

**Issue by irvin** [Metalnem/zinio#5]
on my experience 9 out of 10 mags failed with context deadline exceeded error on one of the pages. 

I'd  try go online with different network and also access from different country through VPN, so it doesn't seems to be a network routine  problem.

**Comment by Metalnem** [comment]
Thanks for the feedback. I'll update the app in the following days to handle such situations in a better way.

**Comment by papexus** [comment]
Same issue here. It always fails after page 100 or so

**Comment by papexus** [comment]
thank you. it works fine

**Comment by irvin** [comment]
work great, thanks!
