### ISSUE TITLE
download skip all adult mags

### ISSUE THREAD

**Issue by irvin** [Metalnem/zinio#8]
The download feature automatically skip all adult mags. 
Perhaps it didn't got list of those title because all zinio platform had default settings to hide adult content.

**Comment by Metalnem** [comment]
Unfortunately, it's not possible to download adult magazines using the Zinio mobile API (see [this](http://imgs.zinio.com/faq/ucm.htm#adult) for more details). Desktop and web application allow them, but using the different API, which my tool doesn't support.
