### ISSUE TITLE
Can't build on a clean Go Docker image

### ISSUE THREAD

**Issue by ConorIA** [Metalnem/zinio#9]
Hi there, I tried to build because I was running into #7 when I was using the latest release. It seems that Unidoc 2.0 has made some significant changes to the way the lib works. I wonder if it is worth it to update the code, so that homebuilders could give it a shot.

**Comment by Metalnem** [comment]
I have just updated the README file with the instructions on how to build the the application from source, please check it out.

**Comment by ConorIA** [comment]
Thanks for the help. However, now I am getting: 
``` bash
root@fd478d200dc5:/usr/src/zinio# go get -u github.com/golang/dep/cmd/dep
root@fd478d200dc5:/usr/src/zinio# dep ensure
/usr/src/zinio is not within a known GOPATH/src
```

**Comment by Metalnem** [comment]
You didn’t download Zinio using go get. You should run the following command:

go get -u github.com/metalnem/zinio

Your zinio directory will the be in $GOPATH/src/github.com/metalnem/zinio—run dep ensure from there.

Nemanja

**Comment by ConorIA** [comment]
Perfect! Thanks for the tip. I actually figured out a workaround just before you posted your comment. This is the sequence of commands, if anyone else is curious:

# On main machine: 
`sudo docker run -it --rm -v "$PWD":/usr/src/zinio -w /usr/src/zinio golang:1.8 bash`

# Within the docker image:
```
go get -u github.com/golang/dep/cmd/dep
export GOPATH=$GOPATH:$PWD
dep ensure
go build
```
